/**
 * generate-prop-tables.ts — build-time prop-table generator.
 *
 * Derives every primitive's prop rows straight from @decklee/schema (the same
 * introspection the CLI AGENTS.md generator uses) so the book's API tables can
 * never drift from the validator. Layers a hand-maintained PROP_NOTES map on top
 * for the human-facing "Notes" column, then writes a typed module the
 * PropApiTable component imports. Deterministic: LAYOUT_IDS order, schema shape
 * order, stable JSON serialization.
 *
 * Run via `tsx src/scripts/generate-prop-tables.ts` (invoked by `prebuild`).
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { buildPropTablesByLayout } from "../../../schema/src/index.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(HERE, "../data/prop-table-data.ts");

/**
 * Human-facing annotations keyed "primitive.propName". Hand-maintained — the
 * one editorial datum the schema can't supply. Missing keys render an empty
 * note (never crash).
 */
const PROP_NOTES: Record<string, string> = {
  "hero.headline": "The single required slot. Renders at hero scale (108px).",
  "hero.subheadline": "Optional supporting line at body scale.",
  "hero.eyebrow": "Optional uppercase kicker in accent-1, wide tracking.",
  "hero.background_treatment": "'color' | 'image' | 'gradient'. 'image' requires image_src.",
  "hero.image_src": "Required when background_treatment is 'image'. Pairs with image_alt.",
  "hero.image_alt": "Required whenever image_src is set — every image needs alt text.",
  "hero.cta_label": "Optional call-to-action line in accent-2.",

  "two-up.left_body": "Required. Text of the left pane (ignored when left_type is 'image').",
  "two-up.right_body": "Required. Text of the right pane (ignored when right_type is 'image').",
  "two-up.left_heading": "Optional heading above the left pane.",
  "two-up.right_heading": "Optional heading above the right pane.",
  "two-up.left_type": "'text' | 'image' | 'stat'. 'image' requires left_image_src.",
  "two-up.right_type": "'text' | 'image' | 'stat'. 'image' requires right_image_src.",
  "two-up.left_image_src": "Required when left_type is 'image'. Pairs with left_image_alt.",
  "two-up.left_image_alt": "Required whenever left_image_src is set.",
  "two-up.right_image_src": "Required when right_type is 'image'. Pairs with right_image_alt.",
  "two-up.right_image_alt": "Required whenever right_image_src is set.",
  "two-up.divider": "Show the hairline divider between panes (default true).",

  "code.code": "Required. The raw source to highlight.",
  "code.language": "Required. highlight.js language id (e.g. 'typescript', 'json').",
  "code.heading": "Optional heading above the code block.",
  "code.highlight_lines": "1-based line numbers; rendered with a non-color border marker.",
  "code.caption": "Optional caption below the code block.",

  "quote.quote": "Required. The quotation text, rendered at h1 scale.",
  "quote.attribution": "Optional attribution line.",
  "quote.context": "Optional secondary context line.",
  "quote.emphasis": "'full' | 'centered' | 'ruled' (default 'centered').",
};

export type PropTableData = {
  primitive: string;
  rows: { prop: string; type: string; required: boolean; notes: string }[];
};

export function buildPropTableData(): PropTableData[] {
  const byLayout = buildPropTablesByLayout();
  return Object.entries(byLayout).map(([primitive, rows]) => ({
    primitive,
    rows: rows.map((row) => ({
      prop: row.name,
      type: row.type,
      required: row.required,
      notes: PROP_NOTES[`${primitive}.${row.name}`] ?? "",
    })),
  }));
}

function emit(): void {
  const data = buildPropTableData();
  const banner =
    "// AUTO-GENERATED by src/scripts/generate-prop-tables.ts — do not edit by hand.\n" +
    "// Regenerated by the `prebuild` npm script before every astro build.\n";
  const body =
    `import type { PropTableData } from "../scripts/generate-prop-tables.js";\n\n` +
    `export const PROP_TABLES: PropTableData[] = ${JSON.stringify(data, null, 2)};\n`;
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, banner + "\n" + body, "utf8");
}

// Only run side effects when invoked as a script, never on import (test-safe).
if (import.meta.url === `file://${process.argv[1]}`) {
  emit();
}
